In [1]:
import pandas as pd
import numpy as np
import re
import string

from utilidades.TextCleaning import clean_text # Para limpiar texto de tweets
from utilidades.TextCorrecting import correct_text # Para corregir palabras

In [2]:
df = pd.read_csv('../train.csv', encoding='ISO-8859-1')

In [3]:
# Selección del largo de las celdas del DataFrame
strech = True

if strech:
    pd.set_option('max_colwidth', 150)
else:
    pd.reset_option('max_colwidth')

In [4]:
df.sample(10, random_state=42)

,id,keyword,location,text,target
2644,3796,destruction,NaN,So you have a new weapon that can cause un-imaginable destruction.,1
2227,3185,deluge,NaN,The f$&amp;@ing things I do for #GISHWHES Just got soaked in a deluge going for pads and tampons. Thx @mishacollins @/@,0
5448,7769,police,UK,DT @georgegalloway: RT @Galloway4Mayor: ÂÃÃThe CoL police can catch a pickpocket in Liverpool Stree... http://t.co/vXIn1gOq4Q,1
132,191,aftershock,NaN,Aftershock back to school kick off was great. I want to thank everyone for making it possible. What a great night.,0
6845,9810,trauma,"Montgomery County, MD",in response to trauma Children of Addicts develop a defensive self - one that decreases vulnerability. (3,0
5559,7934,rainstorm,NaN,@Calum5SOS you look like you got caught in a rainstorm this is amazing and disgusting at the same time,0
1765,2538,collision,NaN,my favorite lady came to our volunteer meeting\nhopefully joining her youth collision and i am excite http://t.co/Ij0wQ490cS,1
1817,2611,crashed,NaN,@brianroemmele UX fail of EMV - people want to insert and remove quickly like a gas pump stripe reader. 1 person told me it crashed the POS,1
6810,9756,tragedy,"Los Angeles, CA",Can't find my ariana grande shirt this is a fucking tragedy,0
4398,6254,hijacking,"Athens,Greece",The Murderous Story Of AmericaÂÃÂªs First Hijacking http://t.co/EYUGk6byxr,1

In [6]:
sentence = df.loc[4398, 'text']
sentence

'The Murderous Story Of AmericaÂ\x89Ã\x9bÂªs First Hijacking http://t.co/EYUGk6byxr'

### Cosas a tener en cuenta.
- La columna `id` puede no ser indicativa de nada para la predicción. Puede ser conveniente usarlo como índice;
- Hay 7613 casos en el train, si se quitan los nulos en `keyword` solo quedan los nulos en `location`. Esto indica que todos los nulos de `keyword` también son nulos en `location`.

In [5]:
df['text'] = df['text'].apply(lambda x: clean_text(x))
# Muestra aleatoria
display(df.sample(10, random_state=42))

,id,keyword,location,text,target
2644,3796,destruction,NaN,so you have a new weapon that can cause unimaginable destruction,1
2227,3185,deluge,NaN,the famp things i do for gishwhes just got soaked in a deluge going for pads and tampons thx,0
5448,7769,police,UK,dt rt ñthe col police can catch a pickpocket in liverpool stree,1
132,191,aftershock,NaN,aftershock back to school kick off was great i want to thank everyone for making it possible what a great night,0
6845,9810,trauma,"Montgomery County, MD",in response to trauma children of addicts develop a defensive self one that decreases vulnerability,0
5559,7934,rainstorm,NaN,you look like you got caught in a rainstorm this is amazing and disgusting at the same time,0
1765,2538,collision,NaN,my favorite lady came to our volunteer meeting hopefully joining her youth collision and i am excite,1
1817,2611,crashed,NaN,ux fail of emv people want to insert and remove quickly like a gas pump stripe reader person told me it crashed the pos,1
6810,9756,tragedy,"Los Angeles, CA",cant find my ariana grande shirt this is a fucking tragedy,0
4398,6254,hijacking,"Athens,Greece",the murderous story of americañs first hijacking,1

### Se corrigen las palabras

In [10]:
#%%time
#df['text'] = df['text'].apply(lambda x: correct_terms(x))

CPU times: user 53min 54s, sys: 58.4 s, total: 54min 52s
Wall time: 54min 52s

Lo anterior tardò 53 minutos con 54 segundos. Se guarda en otro .csv.

In [11]:
#df.reset_index(inplace=True)
#df.to_csv('train_text_corrected.csv', index=False)

In [12]:
df.sample(10, random_state=42)

,id,keyword,location,text,target
2644,3796,destruction,NaN,so you have a new weapon that can cause unimaginable destruction,1
2227,3185,deluge,NaN,the camp things i do for gishwhes just got soaked in a deluge going for pads and tampons the,0
5448,7769,police,UK,dt rt the col police can catch a pickpocket in liverpool street,1
132,191,aftershock,NaN,aftershocks back to school kick off was great i want to thank everyone for making it possible what a great night,0
6845,9810,trauma,"Montgomery County, MD",in response to trauma children of addicts develop a defensive self one that decreases vulnerability,0
5559,7934,rainstorm,NaN,you look like you got caught in a rainstorm this is amazing and disgusting at the same time,0
1765,2538,collision,NaN,my favorite lady came to our volunteer meeting hopefully joining her youth collision and i am excite,1
1817,2611,crashed,NaN,ux fail of em people want to insert and remove quickly like a gas pump stripe reader person told me it crashed the pos,1
6810,9756,tragedy,"Los Angeles, CA",cant find my ariana grande shirt this is a fucking tragedy,0
4398,6254,hijacking,"Athens,Greece",the murderous story of americans first hijacking,1